name: Merge Conflict Checker

on:
  pull_request:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple command
        run: echo "Test workflow triggered!"