name: Merge Conflict Check

on:
  pull_request:
    branches:
      - '**'

jobs:
  check_merge_conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v2

      - name: Fetch Base Branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Check for Merge Conflicts
        run: |
          git merge --no-commit --no-ff origin/${{ github.event.pull_request.head.ref }} || {
            echo "Merge conflicts detected!";
            exit 1;
          }
          echo "No merge conflicts detected."
