name: Merge Conflict Check

on:
  pull_request:
    branches:
      - '**'

jobs:
  check_conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v2

      - name: Check for Merge Conflicts
        uses: olivernybroe/action-conflict-finder@v4.0
