name: Conflict Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '**'  # Detect conflicts when a PR is opened or synchronized.
  push:
    branches:
      - '**'  # Detect conflicts after a PR is merged.

jobs:
  conflict-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch Target Branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Check for Merge Conflicts
        run: |
          git checkout ${{ github.event.pull_request.base.ref }}
          git merge --no-commit --no-ff ${{ github.event.pull_request.head.ref }} || exit 1
        shell: bash
