name: Conflict Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '**'  # Detect conflicts when a PR is opened or synchronized.
  push:
    branches:
      - '**'  # Detect conflicts after a PR is merged.

jobs:
  conflict-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          
      # - name: Configure Git Identity
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
      # - name: Fetch Target Branch
      #   run: |
      #     git fetch origin ${{ github.event.pull_request.base.ref }}

      # - name: Check for Merge Conflicts
      #   run: |
      #     git checkout ${{ github.event.pull_request.base.ref }}
      #     git merge --no-commit --no-ff --allow-unrelated-histories ${{ github.event.pull_request.head.ref }}  || exit 1
      #   shell: bash
      - name: Check Merge Conflicts
        if: ${{ github.event.pull_request.mergeable != false }}
        run: echo "Skipping merge check as GitHub reports no conflicts."

      - name: Throw Error if Mergeable
        if: ${{ github.event.pull_request.mergeable == false }}
        run: |
          echo "Error: Merge conflicts detected. Manual resolution required."
          exit 1