name: PR workflow

on:
  pull_request:
    branches:
      - '**'

jobs:
  Merge-Conflict-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Checkout target branch
        run: git fetch origin ${{ github.base_ref }} && git checkout FETCH_HEAD

      - name: Configure Git committer identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Attempt merge
        run: git merge --no-commit --no-ff ${{ github.head_ref }} --allow-unrelated-histories
        
      - name: Fail if merge conflicts
        run: |
          if [ $? -ne 0 ]; then
            echo "Merge conflicts detected!"
            exit 1
          fi
