name: Debug Workflow

on:
  push:
    branches:
      - '**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              run: echo "Test workflow triggered!"